export interface ArticleModel {
     _id: string;
     _createdAt: string;
     _updatedAt: string;
     publishedAt: string;
     _type: string;
     title: string;
     teaser: string;
     articleSlug: string | '';
     republishArticle: boolean;
     newSlug: any;
     oldSlugs: string[];
     image: {};
     source: string;
     tag: string[];
     tagSlug: string[];
     category: string | '';
     categorySlug: string;
     JournalistName: string;
     JournalistSlug: string;
     JournalistPhoto: string;
     JournalistDetails: [];
     views: number | 0;
     dayInterval: number;
     startIndex: number;
     endIndex: number;
     reading: number;
     previewMode: boolean;
     overview: any[];
}